name: Release Request
description: Use this form to request a new release.
title: '[Release] Release Request for --'
labels: ['release']
body:
  - type: markdown
    attributes:
      value: |
        ## Release Request
        Please fill out the following details to request a new release.
  - type: input
    id: release-version
    attributes:
      label: Release Version
      description: 'Specify the version of the release (e.g., 1.0.0)'
      placeholder: '0.0.0'
    validations:
      required: true
  - type: dropdown
    id: target-environment
    attributes:
      label: Target Environment
      description: 'Select the target environment for the release'
      options:
        - production
        - staging
        - development
    validations:
      required: true
